/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calc;

import jdk.nashorn.internal.runtime.JSType;

/**
 *
 * @author developer
 */
public class calc_gui extends javax.swing.JDialog {

    StringBuilder editor = new StringBuilder();
    StringBuilder Result_text=new StringBuilder();
    int a,b,operator,rs;
    
    

    public calc_gui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        result_pane = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editor_pane = new javax.swing.JTextArea();
        button_8 = new javax.swing.JButton();
        button_7 = new javax.swing.JButton();
        button_9 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_1 = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        button_0 = new javax.swing.JButton();
        mul_button = new javax.swing.JButton();
        div_button = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        sub_button = new javax.swing.JButton();
        equal_Button = new javax.swing.JButton();
        BS_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        editor_pane.setColumns(20);
        editor_pane.setRows(5);
        editor_pane.setName(""); // NOI18N
        jScrollPane1.setViewportView(editor_pane);

        button_8.setText("8");
        button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_8ActionPerformed(evt);
            }
        });

        button_7.setText("7");
        button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_7ActionPerformed(evt);
            }
        });

        button_9.setText("9");
        button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_9ActionPerformed(evt);
            }
        });

        button_5.setText("5");
        button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_5ActionPerformed(evt);
            }
        });

        button_4.setText("4");
        button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_4ActionPerformed(evt);
            }
        });

        button_6.setText("6");
        button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_6ActionPerformed(evt);
            }
        });

        button_2.setText("2");
        button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_2ActionPerformed(evt);
            }
        });

        button_1.setText("1");
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1ActionPerformed(evt);
            }
        });

        button_3.setText("3");
        button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_3ActionPerformed(evt);
            }
        });

        button_0.setText("0");
        button_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_0ActionPerformed(evt);
            }
        });

        mul_button.setText("x");
        mul_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mul_buttonActionPerformed(evt);
            }
        });

        div_button.setText("/");
        div_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                div_buttonActionPerformed(evt);
            }
        });

        add_button.setText("+");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        sub_button.setText("-");
        sub_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_buttonActionPerformed(evt);
            }
        });

        equal_Button.setText("=");
        equal_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equal_ButtonActionPerformed(evt);
            }
        });

        BS_button.setText("C");
        BS_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BS_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(result_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(div_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BS_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(equal_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sub_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(mul_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_9)
                    .addComponent(button_8)
                    .addComponent(button_7)
                    .addComponent(mul_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_6)
                    .addComponent(button_5)
                    .addComponent(button_4)
                    .addComponent(div_button))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_3)
                    .addComponent(button_2)
                    .addComponent(button_1)
                    .addComponent(add_button))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_0)
                    .addComponent(sub_button)
                    .addComponent(equal_Button)
                    .addComponent(BS_button))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_3ActionPerformed
         
        editor.append(3);
        editor_pane.setText(editor.toString());
        Result_text.append(3);
        result_pane.setText(Result_text.toString());
    }//GEN-LAST:event_button_3ActionPerformed

    private void button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1ActionPerformed
        editor.append(1);
        editor_pane.setText(editor.toString());
        Result_text.append(1);
        result_pane.setText(Result_text.toString());
    }//GEN-LAST:event_button_1ActionPerformed

    private void button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_2ActionPerformed
         
        editor.append(2);
        editor_pane.setText(editor.toString());
        Result_text.append(2);
        result_pane.setText(Result_text.toString());
    }//GEN-LAST:event_button_2ActionPerformed

    private void button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_6ActionPerformed
        editor.append(6);
        editor_pane.setText(editor.toString());
        Result_text.append(6);
        result_pane.setText(Result_text.toString());
         
    }//GEN-LAST:event_button_6ActionPerformed

    private void button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_4ActionPerformed
         
        editor.append(4);
        editor_pane.setText(editor.toString());
        Result_text.append(4);
        result_pane.setText(Result_text.toString());
    }//GEN-LAST:event_button_4ActionPerformed

    private void button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_5ActionPerformed
         
        editor.append(5);
        editor_pane.setText(editor.toString());
        Result_text.append(5);
        result_pane.setText(Result_text.toString());
    }//GEN-LAST:event_button_5ActionPerformed

    private void button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_9ActionPerformed
         
        editor.append(9);
        editor_pane.setText(editor.toString());
        Result_text.append(9);
        result_pane.setText(Result_text.toString());
    }//GEN-LAST:event_button_9ActionPerformed

    private void button_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_0ActionPerformed
         
        editor.append(0);
        editor_pane.setText(editor.toString());
        Result_text.append(0);
        result_pane.setText(Result_text.toString());
    }//GEN-LAST:event_button_0ActionPerformed

    private void button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_7ActionPerformed
         
        editor.append(7);
        editor_pane.setText(editor.toString());
        Result_text.append(7);
        result_pane.setText(Result_text.toString());
    }//GEN-LAST:event_button_7ActionPerformed

    private void button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_8ActionPerformed
         
        editor.append(8);
        editor_pane.setText(editor.toString());
        Result_text.append(8);
        result_pane.setText(Result_text.toString());
    }//GEN-LAST:event_button_8ActionPerformed

    private void mul_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mul_buttonActionPerformed
         
        
        editor_pane.setText(editor.toString());
        a=Integer.parseInt(editor.toString());
        Result_text.append("x");
        result_pane.setText(Result_text.toString());
        editor.delete(0, editor.length());
        operator=3;
        
        //System.out.println(a);

    }//GEN-LAST:event_mul_buttonActionPerformed

    private void div_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_div_buttonActionPerformed
         
        //editor.append("/");
        editor_pane.setText(editor.toString());
        a=Integer.parseInt(editor.toString());
        Result_text.append('/');
        result_pane.setText(Result_text.toString());
        editor.delete(0, editor.length());
        operator=4;
    }//GEN-LAST:event_div_buttonActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
         
       // editor.append("+");
        editor_pane.setText(editor.toString());
          a=Integer.parseInt(editor.toString());
          Result_text.append("+");
        result_pane.setText(Result_text.toString());
        editor.delete(0, editor.length());
        operator=1;
    }//GEN-LAST:event_add_buttonActionPerformed

    private void sub_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_buttonActionPerformed
         
        //editor.append("-");
        editor_pane.setText(editor.toString());
         a=Integer.parseInt(editor.toString());
         Result_text.append("-");
        result_pane.setText(Result_text.toString());
        editor.delete(0, editor.length());
        operator=2;
    }//GEN-LAST:event_sub_buttonActionPerformed

    private void BS_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BS_buttonActionPerformed
        Result_text.delete(0, Result_text.length());
        result_pane.setText(Result_text.toString());
        editor.delete(0, editor.length());
        editor_pane.setText(editor.toString());
        
    }//GEN-LAST:event_BS_buttonActionPerformed

    private void equal_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equal_ButtonActionPerformed
        Result_text.append("=");
        result_pane.setText(Result_text.toString());
        editor_pane.setText(editor.toString());
        b=Integer.parseInt(editor.toString());
        
        switch (operator) {
            case 1:
                rs = a + b;
                Result_text.append(rs);
                result_pane.setText(Result_text.toString());
                Result_text.delete(0, Result_text.length());
                break;
            case 2:
                rs = a - b;
                Result_text.append(rs);
                result_pane.setText(Result_text.toString());
                Result_text.delete(0, Result_text.length());
                break;
            case 3:
                rs = a * b;
                Result_text.append(rs);
                result_pane.setText(Result_text.toString());
                Result_text.delete(0, Result_text.length());
                break;
            case 4:
                rs = a / b;
                Result_text.append(rs);
                result_pane.setText(Result_text.toString());
                Result_text.delete(0, Result_text.length());
                break;
                              
                        
        }
        editor.delete(0, editor.length());
        editor_pane.setText(editor.toString());
        

        
    }//GEN-LAST:event_equal_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                calc_gui dialog = new calc_gui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BS_button;
    private javax.swing.JButton add_button;
    private javax.swing.JButton button_0;
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    private javax.swing.JButton button_5;
    private javax.swing.JButton button_6;
    private javax.swing.JButton button_7;
    private javax.swing.JButton button_8;
    private javax.swing.JButton button_9;
    private javax.swing.JButton div_button;
    private javax.swing.JTextArea editor_pane;
    private javax.swing.JButton equal_Button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mul_button;
    private javax.swing.JLabel result_pane;
    private javax.swing.JButton sub_button;
    // End of variables declaration//GEN-END:variables
}
