/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filter_jdbc;

import java.awt.Component;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.runtime.regexp.joni.ast.ConsAltNode;

/**
 *
 * @author developer
 */
public class delete_panel extends javax.swing.JPanel {
    String DelString="";
    
    /**
     * Creates new form delete_panel
     */
    JFrame jFrame=new JFrame();
    
    public delete_panel() {
        initComponents();        
        //jFrame.add(DelPan);
        JOptionPane.showMessageDialog(jFrame,DelPan , "Delete dialog box", HEIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DelPan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        get_idTextFlied = new javax.swing.JTextField();
        getIDButton = new javax.swing.JButton();

        jLabel1.setText("Enter the ID you have to delete");

        get_idTextFlied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_idTextFliedActionPerformed(evt);
            }
        });

        getIDButton.setText("Delete");
        getIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getIDButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DelPanLayout = new javax.swing.GroupLayout(DelPan);
        DelPan.setLayout(DelPanLayout);
        DelPanLayout.setHorizontalGroup(
            DelPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DelPanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(get_idTextFlied, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getIDButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DelPanLayout.setVerticalGroup(
            DelPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DelPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DelPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(get_idTextFlied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getIDButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DelPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(DelPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void get_idTextFliedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_idTextFliedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_get_idTextFliedActionPerformed

    private void getIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getIDButtonActionPerformed
        DelString=get_idTextFlied.getText();
        jFrame.setVisible(false);
    }//GEN-LAST:event_getIDButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DelPan;
    private javax.swing.JButton getIDButton;
    private javax.swing.JTextField get_idTextFlied;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
