/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filter_jdbc;

import com.sun.prism.j2d.J2DPipeline;
import java.util.Vector;
import javax.net.ssl.SSLEngineResult;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.PopupFactory;
import jdk.nashorn.internal.scripts.JO;

/**
 *
 * @author developer
 */
public class insert_panel extends javax.swing.JPanel {

    Vector<String> Values= new Vector<>();;
    Vector<String> colnames = new Vector<>();
    int count = 0, ColSize = 0;
    JFrame jFrame = new JFrame();
    

    /**
     * Creates new form insert_panel
     */
   

    public insert_panel(Vector<String> names) {
       
        initComponents();
        colnames = names;
        ColSize = colnames.size();
        //InsertField.setText(colnames.get(count));
        InsertTextField.setText("Press Next to get Fields ");        
        Values.clear();

       JOptionPane.showMessageDialog(jFrame, this, "Insert Dialog box", JOptionPane.DEFAULT_OPTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        InsertField = new javax.swing.JLabel();
        InsertButton = new javax.swing.JButton();
        InsertTextField = new javax.swing.JTextField();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        InsertField.setText("Insert Field  ");

        InsertButton.setText("Next");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });
        InsertButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InsertButtonKeyPressed(evt);
            }
        });

        InsertTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(InsertField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(InsertTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertButton))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
               
        if ((ColSize>count)&&(count>0)){
            InsertField.setText(colnames.get(count));
            Values.add(InsertTextField.getText());
            InsertTextField.setText("");
                        
            
        }
        else if (count==0){
            InsertField.setText(colnames.get(count));
            InsertTextField.setText("");
        }
        else if (ColSize== count){
            
            Values.add(InsertTextField.getText());
            jFrame.setVisible(false);
        }
        
        count = count + 1;


    }//GEN-LAST:event_InsertButtonActionPerformed

    private void InsertTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertTextFieldActionPerformed

    private void InsertButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InsertButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertButtonKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertButton;
    private javax.swing.JLabel InsertField;
    private javax.swing.JTextField InsertTextField;
    public javax.swing.JPanel Panel;
    // End of variables declaration//GEN-END:variables
}
